### ISSUE TITLE
ATree: Fortitude has wrong multiplier

### ISSUE THREAD

**Issue by hppeng-wynn** [hppeng-wynn/hppeng-wynn.github.io#131]
100% -> 60%

![image](https://user-images.githubusercontent.com/77039964/179116886-f542b6f7-cc33-4501-b453-cb1dcc4ed8a9.png)

also check if we have this done correctly
![image](https://user-images.githubusercontent.com/77039964/179116908-5f70089b-0aee-49c1-96ff-0a79456f1d8e.png)
 (idr if we even implemented it, if not implemented then whatever)
 
 also check these 
![image](https://user-images.githubusercontent.com/77039964/179116938-e5a54895-b8cf-470e-aca5-ae38bca3a266.png)

**Comment by aspiepuppy** [comment]
Will get to this eventually

**Comment by hppeng-wynn** [comment]
#136
