### ISSUE TITLE
Alter calculations for cherry bomb major id

### ISSUE THREAD

**Issue by 764hotshot** [hppeng-wynn/hppeng-wynn.github.io#244]
Right now smoke bomb dmg doesn't change if you have the cherry bomb major id active 
This worked in wynnbuilder and would be great if you could port it 
<img width="265" alt="image" src="https://user-images.githubusercontent.com/42724811/209587200-9af11ad3-5243-4b77-a0e1-725a870a3ae5.png">

**Comment by hppeng-wynn** [comment]
finally resolved! :)
