### ISSUE TITLE
Misc: Fix hyperlink to credits.txt

### ISSUE THREAD

**Issue by hppeng-wynn** [hppeng-wynn/hppeng-wynn.github.io#83]
should be easy fix

**Comment by lodenrogue** [comment]
Correct link is this? https://raw.githubusercontent.com/hppeng-wynn/hppeng-wynn.github.io/master/credits.txt

**Comment by hppeng-wynn** [comment]
https://hppeng-wynn.github.io/credits.txt
just this

**Comment by lodenrogue** [comment]
I can give this a shot

**Comment by lodenrogue** [comment]
PR: https://github.com/hppeng-wynn/hppeng-wynn.github.io/pull/85
